// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css'; // Asegúrate de que la ruta a tu CSS sea correcta
import { Providers } from '@/components/providers'; // Importa tu componente de providers
import Header from '@/components/header'; // Importa tu componente de Header
import Footer from '@/components/footer'; // Importa tu componente de Footer

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        < Header /> {/* Incluye el Header en el layout */}
        <div style={{ paddingTop: '150px' /* Adjust based on your header height */ }}>
          <Providers> {/* Envuelve tus hijos con el Provider de Redux */}
            {children}
          </Providers>
        </div>
        <Footer/>
      </body>
    </html>
  );
}